# Generated by Django 3.2.25 on 2025-12-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['-created_at'], name='contact_created_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['status'], name='contact_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['email'], name='contact_email_idx'),
        ),
    ]
