# Generated by Django 3.2.25 on 2025-11-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload car image', null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide image URL', null=True),
        ),
    ]
