# Generated by Django 3.2.25 on 2025-11-03 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20251103_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image_url',
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload car image', upload_to='cars/')),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary/cover image')),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'verbose_name': 'Car Image',
                'verbose_name_plural': 'Car Images',
                'ordering': ['-is_primary', 'order', 'uploaded_at'],
            },
        ),
    ]
