# Generated by Django 3.2.25 on 2025-11-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20251103_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('van', 'Van'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('wagon', 'Wagon'), ('convertible', 'Convertible'), ('pickup', 'Pickup'), ('minivan', 'Minivan')], help_text='Body type/style of the vehicle', max_length=20, null=True),
        ),
    ]
