# Generated by Django 3.2.25 on 2025-12-05 07:55

import cars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_body_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100, validators=[cars.models.validate_brand_model]),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=50, validators=[cars.models.validate_color]),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.DecimalField(decimal_places=1, help_text='Engine size in liters', max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(15.0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.TextField(blank=True, help_text="Comma-separated list of features (e.g., 'GPS, Leather Seats, Sunroof')", max_length=2000),
        ),
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(help_text='Mileage in kilometers', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, validators=[cars.models.validate_brand_model]),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17, null=True, unique=True, validators=[cars.models.validate_vin]),
        ),
    ]
