# Generated by Django 3.2.25 on 2025-12-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20251205_0755'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand', 'model'], name='brand_model_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price'], name='price_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['year'], name='year_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['-created_at'], name='created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_available', 'is_featured'], name='availability_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['fuel_type'], name='fuel_type_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['transmission'], name='transmission_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['body_type'], name='body_type_idx'),
        ),
    ]
