# Generated by Django 3.2.25 on 2025-12-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20251205_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
